apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argo-cd-cert
spec:
  secretName: argocd-secret
  issuerRef:
    name: argo-cd-issuer
    kind: Issuer
  commonName: argo-dev.ssc-eks-ekm.ssc.band
  dnsNames:
  - argo-dev.ssc-eks-ekm.ssc.band
