apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: argo-cd-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: amatyushentsev@gmail.com
    privateKeySecretRef:
      name: letsencrypt
    solvers:
    # An empty 'selector' means that this solver matches all domains
    - selector: {}
      http01:
        ingress:
          class: nginx
