apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-auth
  namespace: argocd
spec:
  encryptedData:
    dex.github.clientSecret: AgAum/tTY0ctx/cpQrP3p1mS5Q9YgKD615k7dU2qn5mxTdKPw7dS07C06ZCS/Zfd+eaUP5punm4Ln9HFiMkoSJOVmBFeusHdHoHenBhsCi/NQBU2Dwb+lj63rdhYMj3QTJ+HAa4ZuDu0y0vhNhCz68h9NfH3CErSFesgDlZQs/ovaHGqoVR6kBu2HZtqTNHfcxTmfl9e/SlLftsCvzTMtEEBbqW67T0FEqs4k7udrl0oIpAcUSFxEPmWQNjoALu0BziVdVxW6dY5aG/K/aqgYRH6NSgjSDov7LVI3xG2QLfeIN9C8s3fsnGrFephldmv/mL+bZ+iEdwps8NKuXNh+4ABVZyrT/zRZAREDlvQ5iHATWCv+xcgjSWl+hUe8NgyGvHsf34PUtI/udLkZIb1KSsl7Dquu5Hb1mZMJogS915UlL68Ejh7mb9ghi3FTpDgdPEBpk1YRVLIEvK8m9YacdKV0ODNxQYpKieWT4fvUwXFviw68ls2lFrjD4GeEHC38ph1I2Hh0slqykVf8GjUkGjZpwu+A6sKYwlg5B9TI0tvqM5Le+OA727Z5JfDDZMQDuhqI3TTNybHRXzMKnAe5C5uCRoWk7VVEvrfsiKefcWGtd66YOIEs7hHrouA+4EP2g8AbeEoNS9L9BNnWiMaL14QUQXxHc++GUwfEravDzB3arPdC15MYaLHXxTxXWy17rhGZcxYirJVcXaSykihz1zI7ezgIjlChC/T+Pmud1LLGVuBevDEFFt4
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: argocd
