apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-write
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argo-workflows-read-write-namespaced
subjects:
  - kind: ServiceAccount
    name: read-write
