apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: argocd
  annotations: 
    argocd.argoproj.io/client-side-apply-migration-manager: "kube-apiserver"
  ### Just as a prevention, we do not want Argo CD to self delete
  # finalizers:
  #   - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argocd
    repoURL: https://github.com/argoproj/argoproj-deployments
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    ### Disable Argo CD auto-sync to better control updates of what is merged upstream
    # automated:
    #   prune: true
    #   selfHeal: true
