apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dex
spec:
  destination:
    namespace: dex
    server: https://kubernetes.default.svc
  project: default
  source:
    path: dex
    repoURL: https://github.com/argoproj/argoproj-deployments
    targetRevision: HEAD
