apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-operator
  namespace: argocd
spec:
  source:
    repoURL: https://github.com/istio/istio
    path: manifests/charts/istio-operator
    targetRevision: release-1.20
    helm:
      parameters:
        - name: enableCRDTemplates
          value: 'true'
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-operator
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
