apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-addons
spec:
  source:
    path: samples/addons
    repoURL: https://github.com/istio/istio
    targetRevision: release-1.7
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  project: default
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
