apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - base/monitoring-namespace.yaml
  - base/prometheus-redirect-service.yaml
  - https://github.com/argoproj-labs/argocd-extension-metrics/manifests?ref=v1.0.3

images:
  - name: quay.io/argoprojlabs/argocd-extension-metrics
    newTag: v1.0.3

patches:
  - path: overlays/patch-priority-class.yaml
    target:
      kind: Deployment
