apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: team-backend
  namespace: argocd
spec:
  description: Project for team-backend namespace Applications and ApplicationSets

  sourceNamespaces:
    - team-backend

  destinations:
    - namespace: 'team-backend-*'
      server: https://kubernetes.default.svc
    - namespace: 'backend-*'
      server: https://kubernetes.default.svc

  sourceRepos:
    - https://github.com/argoproj/argocd-example-apps

  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
