apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: argo-workflows-cert
spec:
  secretName: argo-workflows-secret
  issuerRef:
    name: argo-workflows-issuer
    kind: Issuer
  commonName: workflows.apps.argoproj.io
  dnsNames:
  - workflows.apps.argoproj.io
