apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argo-workflows-webhook-clients
  namespace: argo
spec:
  encryptedData:
    github.com: AgAUOhspWnbPFFbqyYU1kFs6C7b/9A50fSodsZBunGoG3b2Kc0bOMWMQZPwL+5D+EQk2e1y5ddQup+ReTxgmxX0c4yxYMbKtVu2h+rTbAWiYXXjscd0WLkaWdC+a1TBpZ3KKgmydPb8iNV93W/vdbNQS5RX5OWWvIzXMPve3mG8VcfCzTJNvChkBk3KbxjmC9sJI9ER9lifN3LQz8esfrbkz9e7lc3KqNpVQ3LXWLYjlFCukhUNdwWAOK9O1f0VJRefNPo3Km9WRAv38FoEBRlxLQyogTU3pBU7NMomkHU9wrYWuIINZLZ0dzYwpprUdSOHaGLdY+yn45ddOk7CMPQ7MbeuVD2ZchCm9ge/4i4Sdegb9ZnnM8fpT+NndXoTEOs8rVsZjZC45vzErzhPUeUADqVEkkOTJJUX/WMbaNX4cVCPtxWCHMjAHL96qILMiE7VRDYNUqr7TkA0kCNH6MAnqqfuLpthSjDrqAI/ilagNTajHlk2fwsr8h0SRG+pTatx8GT2wwSDd0YDe6GWfP7yR16T4KHXtzQxNTT2dynPnPueaGPn1/gbxs5zsgsgmD8j+/qHmaQoCnz3fMvQQlNkwtVtv2rI3Q6HUglBPkpMOKOW/o0oO/C3f377WZfCei7xb2Nl7OLxITI0i3yRWCcYswGvjt7tTl5+1lnJ1tg/tpGJyolSPnDmdqN4X04HzIF3t/57LAdUbjTYUlspXhG6AsVf4dfbW+cTUiYvKyQ==
