apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-server-binding
  namespace: workflow-playground # Gives permission in the managed namespace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argo-workflows-argo-server-role
subjects:
  - kind: ServiceAccount
    name: argo-server
    namespace: argo
