apiVersion: apps/v1
kind: Deployment
metadata:
  name: workflow-controller
spec:
  template:
    spec:
      containers:
        - name: workflow-controller
          args:
            - --namespaced
            - --managed-namespace
            - workflow-playground
