apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dex-cert
spec:
  secretName: dex-secret
  issuerRef:
    name: dex-issuer
    kind: Issuer
  commonName: dex.apps.argoproj.io
  dnsNames:
    - dex.apps.argoproj.io
