apiVersion: v1
kind: Secret
metadata:
  name: user-default-login.service-account-token
  annotations:
    kubernetes.io/service-account.name: user-default-login
type: kubernetes.io/service-account-token
