apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: artifacts
spec:
  schedule: '*/5 * * * *'
  workflowSpec:
    serviceAccountName: workflow
    workflowTemplateRef:
      name: artifacts