apiVersion: argoproj.io/v1alpha1
kind: WorkflowEventBinding
metadata:
  name: event-consumer
spec:
  event:
    selector: metadata["x-github-event"] != nil
  submit:
    workflowTemplateRef:
      name: github-event
    arguments:
      parameters:
        - name: message
          valueFrom:
            event: payload.message