apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: github-event
spec:
  entrypoint: main
  serviceAccountName: workflow
  arguments:
    parameters:
      - name: message
  templates:
    - name: main
      inputs:
        parameters:
          - name: message
            value: "{{workflow.parameters.message}}"
      container:
        image: alpine:3.6
        command: [ sh, -c ]
        args: [ "echo", "{{inputs.parameters.message}}" ]
